(begin (pr-update-config '(("config_log_location" . #t) 
                           ("config_enable_log_server" . #t) 
                           ("config_http_encrypt" . #f) 
                           ("config_restrict_data_wifi" . #t) 
                           ("config_json_refresh_interval" . "3600") 
                           ("config_dialog_count" . "4") 
                           ("config_probes_enabled" . #t) 
                           ("config_streaming_jackson_upload_interval" . "300") 
                           ("config_http_upload_size" . "0") 
                           ("config_enable_streaming_jackson_data_server" . #t) 
                           ("config_log_server_uri" . "http://skyfall.aetherial.net/pr/log") 
                           ("check_scheme_config" . #t) 
                           ("config_mute_warnings" . #f) 
                           ("config_log_heartbeat" . #t) 
                           ("config_json_haptic_pattern" . "60") 
                           ("config_enable_data_server" . #f) 
                           ("config_http_upload_interval" . "0") 
                           ("config_external_storage" . #t) 
                           ("config_show_background" . #t) 
                           ("config_default_notification_sound" . "0") 
                           ("config_data_server_uri" . "http://skyfall.aetherial.net/pr/") 
                           ("config_http_archive" . #f) 
                           ("config_log_upload_interval" . "600") 
                           ("config_user_id" . "galaxy-nexus-tester") 
                           ("config_password" . "") 
                           ("config_hockey_update" . #f) 
                           ("config_http_liberal_ssl" . #t) 
                           ("config_preferred_hash_function" . "MD5") 
                           ("config_restrict_log_wifi" . #t) 
                           ("config_streaming_jackson_upload_size" . "262114") 
                           ("config_record_snapshot_audio" . #f))) 
        (begin 
               (pr-update-probe '(("frequency" . 0L) 
                                  ("enabled" . #t) 
                                  ("threshold" . 0.0) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.devices.PebbleProbe")))
               (pr-update-probe '(("enabled" . #t) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.SignificantMotionProbe")))
               (pr-update-probe '(("frequency" . 30000L) 
                                  ("enabled" . #t) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.ActivityDetectionProbe")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.AccelerometerFrequencyFeature")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.TemperatureProbeBasicStatisticsFeature")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.ProximityProbeBasicStatisticsFeature")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.PressureProbeBasicStatisticsFeature")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.LightProbeBasicStatisticsFeature")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.MagneticFieldBasicStatisticsFeature")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.GyroscopeBasicStatisticsFeature")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.AccelerometerBasicStatisticsFeature")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.SunriseSunsetFeature")))
               (pr-update-probe '(("enabled" . #t) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.features.WeatherUndergroundFeature")))
               (pr-update-probe '(("frequency" . 300000L) 
                                  ("enabled" . #t) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.WifiAccessPointsProbe")))
               (pr-update-probe '(("frequency" . 0L) 
                                  ("enabled" . #t) 
                                  ("threshold" . 1.0) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.TemperatureProbe")))
               (pr-update-probe '(("frequency" . 86400000L) 
                                  ("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.SoftwareInformationProbe")))
               (pr-update-probe '(("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.ScreenProbe")))
               (pr-update-probe '(("frequency" . 86400000L) 
                                  ("enabled" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.RunningSoftwareProbe")))
               (pr-update-probe '(("frequency" . 300000L) 
                                  ("config_probe_robot_scheme_config" . #f) 
                                  ("enabled" . #t) 
                                  ("config_probe_robot_json_config" . #f) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.RobotHealthProbe")))
               (pr-update-probe '(("frequency" . 0L) 
                                  ("enabled" . #t) 
                                  ("threshold" . 5.0) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.ProximityProbe")))
               (pr-update-probe '(("frequency" . 1L) 
                                  ("enabled" . #t) 
                                  ("threshold" . 0.0) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.PressureProbe")))
               (pr-update-probe '(("frequency" . 0L) 
                                  ("enabled" . #t) 
                                  ("threshold" . 1.0) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.MagneticFieldProbe")))
               (pr-update-probe '(("frequency" . 60000L) 
                                  ("enabled" . #t) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.LocationProbe")))
               (pr-update-probe '(("frequency" . 0L) 
                                  ("enabled" . #t) 
                                  ("threshold" . 10.0) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.LightProbe")))
               (pr-update-probe '(("frequency" . 86400000L) 
                                  ("enabled" . #t) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.HardwareInformationProbe")))
               (pr-update-probe '(("frequency" . 1L) 
                                  ("enabled" . #t) 
                                  ("threshold" . 0.0) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.GyroscopeProbe")))
               (pr-update-probe '(("enabled" . #t) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.BatteryProbe")))
               (pr-update-probe '(("frequency" . 1L) 
                                  ("enabled" . #t) 
                                  ("threshold" . 0.0) 
                                  ("name" . "edu.northwestern.cbits.purple_robot_manager.probes.builtin.AccelerometerProbe")))))